pretrained_model_name_or_path = "flux1-dev.safetensors"
clip_l = "clip_l.safetensors"
t5xxl = "t5xxl_fp16.safetensors"
ae = "ae.safetensors"
resolution = "1024,1024"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 1024
bucket_reso_steps = 64
save_model_as = "safetensors"
train_data_dir = "/img"
output_dir = "/model"
output_name = "flux_exp3"
learning_rate = 1e-5
max_train_epochs = 100
save_every_n_epochs = 10
gradient_checkpointing = true
mixed_precision = "bf16"
save_precision = "bf16"
seed = 42
mixed_precision = "bf16"
optimizer_type = "adafactor"
optimizer_args = ["relative_step=False", "scale_parameter=False", "warmup_init=False"]
lr_scheduler = "constant_with_warmup"
max_grad_norm = 0.0
persistent_data_loader_workers = true
max_data_loader_n_workers = 2
sdpa = true
highvram = true
cache_text_encoder_outputs_to_disk = true
cache_latents_to_disk = true
timestep_sampling = "shift"
discrete_flow_shift = 3.1582
model_prediction_type = "raw"
guidance_scale = 1.0
fused_backward_pass = true
blocks_to_swap = 12
xformers = true
